server:
  address: 127.0.0.1
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true

game:
  gamesCount: 3
  seatsCount: 2
  deckStartValue: 17
  deckEndValue: 52
  minHandOnNewTurn: 6